server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/test1?serverTimezone=Asia/Seoul
    username: test1
    password: bitc5600
    driver-class-name: com.mysql.cj.jdbc.Driver 
